import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { act, render, screen, waitFor } from '@testing-library/react';
import userEvent from '@testing-library/user-event';
import { MemoryRouter } from 'react-router-dom';
import { api } from '../lib/api';
import { validateImage } from '../lib/draft';
import { acknowledge, saveQueued } from '../lib/queue';
import type { AnalysisResult, IncidentRecord } from '../lib/api-types';
import ReportPage from './report';
vi.mock('../App', () => ({ useConnection: () => ({ online:true,changed:vi.fn() }) }));
vi.mock('../lib/queue', () => ({ saveQueued:vi.fn(),acknowledge:vi.fn() }));
vi.mock('../lib/draft', async original => ({ ...await original<typeof import('../lib/draft')>(),validateImage:vi.fn() }));
const result: AnalysisResult = { analysis:{ incident_type:'Flood',summary:'Analysis of OLD photo',people_affected:null,vulnerable_people:[],reported_needs:[],location_context:'School',language:'English',image_observations:['OLD photo observation'],confidence:null,verification_required:true },analysis_mode:'live',model_id:'review-double',warnings:[] };
afterEach(() => vi.unstubAllGlobals());
beforeEach(() => {
  vi.mocked(validateImage).mockReset().mockResolvedValue(undefined);
  vi.mocked(saveQueued).mockReset().mockResolvedValue(undefined);
  vi.mocked(acknowledge).mockReset().mockResolvedValue(undefined);
  vi.stubGlobal('URL',class extends URL { static createObjectURL(){return 'blob:review'} static revokeObjectURL(){} });
});
it('must not attach old-photo analysis to a replacement that finishes decoding during inference',async () => {
  render(<MemoryRouter><ReportPage/></MemoryRouter>);
  const user=userEvent.setup();
  await user.type(screen.getByLabelText(/What happened?/),'Flood at school');
  await user.type(screen.getByLabelText(/Where is it?/),'School');
  await user.upload(screen.getByLabelText('Incident photo'),new File(['old'],'old.png',{type:'image/png'}));
  await screen.findByText('old.png');
  let finishValidation!: () => void;
  vi.mocked(validateImage).mockImplementationOnce(() => new Promise<void>(resolve => { finishValidation=resolve; }));
  await user.upload(screen.getByLabelText('Incident photo'),new File(['new'],'new.png',{type:'image/png'}));
  let finishInference!: (value:AnalysisResult) => void;
  vi.spyOn(api,'analyze').mockImplementation(() => new Promise(resolve => { finishInference=resolve; }));
  vi.spyOn(api,'create').mockImplementation(async submission => ({id:'server',client_report_id:submission.client_report_id,sync_status:'synced'} as IncidentRecord));
  await user.click(screen.getByRole('button',{name:'Help describe this'}));
  await act(async () => { finishValidation(); });
  await screen.findByText('new.png');
  if (finishInference) await act(async () => { finishInference(result); });
  await user.click(screen.getByRole('button',{name:/^Send report/}));
  await waitFor(() => expect(saveQueued).toHaveBeenCalled());
  const saved=vi.mocked(saveQueued).mock.calls[0][0];
  expect(saved.image_name).toBe('new.png');
  expect(saved.analysis_result).toBeNull();
});
